import type{ Product } from "../types";


export const PRODUCTS: Product[] = [
  // ─── SMARTPHONES ────────────────────────────────────────────────
  {
    id: 1,
    name: "iPhone 15 Pro Max",
    slug: "iphone-15-pro-max",
    category: "Smartphones",
    brand: "Apple",
    price: 1199,
    oldPrice: 1299,
    rating: 4.8,
    reviewCount: 342,
    image: "/images/iphone.jpg",
    images: ["/images/iphone.jpg", "/images/iphone-2.jpg", "/images/iphone-3.jpg"],
    shortDescription: "Titanium design with A17 Pro chip and pro camera system.",
    fullDescription:
      "The iPhone 15 Pro Max features a strong, light titanium design, the powerful A17 Pro chip, and a versatile pro camera system with 5x optical zoom. A stunning Super Retina XDR display makes everything look incredible.",
    stock: 24,
    featured: true,
    trending: true,
    specifications: {
      Brand: "Apple",
      Model: "iPhone 15 Pro Max",
      Storage: "256GB",
      RAM: "8GB",
      Display: '6.7" OLED ProMotion',
      Battery: "4441 mAh",
      Connectivity: "5G, Wi-Fi 6E, USB-C",
      Warranty: "1 Year",
    },
    colors: ["Natural Titanium", "Blue Titanium", "Black Titanium"],
    warranty: "1 Year",
  },
  {
    id: 2,
    name: "Samsung Galaxy S24 Ultra",
    slug: "samsung-galaxy-s24-ultra",
    category: "Smartphones",
    brand: "Samsung",
    price: 1099,
    rating: 4.7,
    reviewCount: 289,
    image: "/images/s24ultra.jpg",
    images: ["/images/s24ultra.jpg", "/images/s24ultra-2.jpg", "/images/s24ultra-3.jpg"],
    shortDescription: "Flagship Android phone with built-in S Pen and 200MP camera.",
    fullDescription:
      "Galaxy S24 Ultra packs a 200MP camera system, a built-in S Pen, and Galaxy AI features into a precision-crafted titanium frame, all driven by a massive 6.8\" QHD+ display.",
    stock: 31,
    featured: true,
    trending: false,
    specifications: {
      Brand: "Samsung",
      Model: "Galaxy S24 Ultra",
      Storage: "256GB",
      RAM: "12GB",
      Display: '6.8" QHD+ AMOLED',
      Battery: "5000 mAh",
      Connectivity: "5G, Wi-Fi 6E, USB-C",
      Warranty: "1 Year",
    },
    colors: ["Titanium Gray", "Titanium Black", "Titanium Violet"],
    warranty: "1 Year",
  },
  {
    id: 3,
    name: "Google Pixel 9 Pro",
    slug: "google-pixel-9-pro",
    category: "Smartphones",
    brand: "Google",
    price: 899,
    rating: 4.6,
    reviewCount: 156,
    image: "/images/pixel9pro.jpg",
    images: ["/images/pixel9pro.jpg", "/images/pixel9pro-2.jpg", "/images/pixel9pro-3.jpg"],
    shortDescription: "Pure Android experience with best-in-class computational photography.",
    fullDescription:
      "Pixel 9 Pro brings the smartest version of Android with the Google Tensor G4 chip, an advanced triple camera system, and seamless AI features baked right into the OS.",
    stock: 18,
    featured: false,
    trending: false,
    specifications: {
      Brand: "Google",
      Model: "Pixel 9 Pro",
      Storage: "128GB",
      RAM: "12GB",
      Display: '6.3" OLED 120Hz',
      Battery: "4700 mAh",
      Connectivity: "5G, Wi-Fi 6E, USB-C",
      Warranty: "1 Year",
    },
    colors: ["Obsidian", "Porcelain", "Wintergreen"],
    warranty: "1 Year",
  },
  {
    id: 4,
    name: "OnePlus 12",
    slug: "oneplus-12",
    category: "Smartphones",
    brand: "OnePlus",
    price: 799,
    oldPrice: 899,
    rating: 4.5,
    reviewCount: 98,
    image: "/images/oneplus12.jpg",
    images: ["/images/oneplus12.jpg", "/images/oneplus12-2.jpg", "/images/oneplus12-3.jpg"],
    shortDescription: "Flagship killer with 100W fast charging and Hasselblad camera.",
    fullDescription:
      "The OnePlus 12 delivers flagship performance at a refreshing price, with a buttery-smooth 120Hz display, Hasselblad-tuned cameras, and blazing 100W SUPERVOOC charging.",
    stock: 27,
    featured: false,
    trending: true,
    specifications: {
      Brand: "OnePlus",
      Model: "12",
      Storage: "256GB",
      RAM: "16GB",
      Display: '6.82" AMOLED 120Hz',
      Battery: "5400 mAh",
      Connectivity: "5G, Wi-Fi 7, USB-C",
      Warranty: "1 Year",
    },
    colors: ["Flowy Emerald", "Silky Black"],
    warranty: "1 Year",
  },

  // ─── LAPTOPS ────────────────────────────────────────────────────
  {
    id: 5,
    name: 'MacBook Pro 16" M3',
    slug: "macbook-pro-16",
    category: "Laptops",
    brand: "Apple",
    price: 2499,
    rating: 4.9,
    reviewCount: 421,
    image: "/images/mbp16.jpg",
    images: ["/images/mbp16.jpg", "/images/mbp16-2.jpg", "/images/mbp16-3.jpg"],
    shortDescription: "Supercharged for pros with the M3 Pro chip.",
    fullDescription:
      'MacBook Pro 16" delivers exceptional performance with the M3 Pro chip, a stunning Liquid Retina XDR display, and all-day battery life — built for the most demanding pro workflows.',
    stock: 14,
    featured: true,
    trending: false,
    specifications: {
      Brand: "Apple",
      Model: "MacBook Pro 16",
      Processor: "Apple M3 Pro",
      RAM: "18GB",
      Storage: "512GB SSD",
      Display: '16.2" Liquid Retina XDR',
      Battery: "Up to 22 hrs",
      Warranty: "1 Year",
    },
    colors: ["Space Black", "Silver"],
    warranty: "1 Year",
  },
  {
    id: 6,
    name: "Dell XPS 15",
    slug: "dell-xps-15",
    category: "Laptops",
    brand: "Dell",
    price: 1799,
    rating: 4.6,
    reviewCount: 187,
    image: "/images/xps15.jpg",
    images: ["/images/xps15.jpg", "/images/xps15-2.jpg", "/images/xps15-3.jpg"],
    shortDescription: "Premium Windows ultrabook with InfinityEdge display.",
    fullDescription:
      "Dell XPS 15 combines a gorgeous InfinityEdge OLED display with serious performance, wrapped in a precision-machined aluminum chassis built for creators and professionals.",
    stock: 11,
    featured: false,
    trending: false,
    specifications: {
      Brand: "Dell",
      Model: "XPS 15",
      Processor: "Intel Core i7-13700H",
      RAM: "16GB",
      Storage: "1TB SSD",
      Display: '15.6" 3.5K OLED',
      Battery: "Up to 13 hrs",
      Warranty: "1 Year",
    },
    warranty: "1 Year",
  },
  {
    id: 7,
    name: "ASUS ROG Zephyrus G14",
    slug: "asus-rog-zephyrus-g14",
    category: "Laptops",
    brand: "Asus",
    price: 1599,
    oldPrice: 1799,
    rating: 4.7,
    reviewCount: 203,
    image: "/images/zephyrusg14.jpg",
    images: ["/images/zephyrusg14.jpg", "/images/zephyrusg14-2.jpg", "/images/zephyrusg14-3.jpg"],
    shortDescription: "Compact gaming powerhouse with RTX graphics.",
    fullDescription:
      "The ROG Zephyrus G14 squeezes desktop-class gaming performance into a stunningly portable chassis, with a vivid high-refresh display and a customizable AniMe Matrix lid.",
    stock: 8,
    featured: false,
    trending: true,
    specifications: {
      Brand: "Asus",
      Model: "ROG Zephyrus G14",
      Processor: "AMD Ryzen 9 8945HS",
      RAM: "16GB",
      Storage: "1TB SSD",
      Display: '14" QHD+ 165Hz',
      GPU: "RTX 4060",
      Warranty: "1 Year",
    },
    warranty: "1 Year",
  },
  {
    id: 8,
    name: "Lenovo ThinkPad X1 Carbon",
    slug: "lenovo-thinkpad-x1-carbon",
    category: "Laptops",
    brand: "Lenovo",
    price: 1499,
    rating: 4.5,
    reviewCount: 142,
    image: "/images/x1carbon.jpg",
    images: ["/images/x1carbon.jpg", "/images/x1carbon-2.jpg", "/images/x1carbon-3.jpg"],
    shortDescription: "Ultra-light business laptop built for durability.",
    fullDescription:
      "ThinkPad X1 Carbon is engineered for business — incredibly light, MIL-SPEC tested for durability, with a legendary keyboard and enterprise-grade security features.",
    stock: 20,
    featured: false,
    trending: false,
    specifications: {
      Brand: "Lenovo",
      Model: "ThinkPad X1 Carbon",
      Processor: "Intel Core i7-1365U",
      RAM: "16GB",
      Storage: "512GB SSD",
      Display: '14" WUXGA',
      Battery: "Up to 15 hrs",
      Warranty: "3 Year",
    },
    warranty: "3 Year",
  },

  // ─── HEADPHONES ─────────────────────────────────────────────────
  {
    id: 9,
    name: "Sony WH-1000XM5",
    slug: "sony-wh1000xm5",
    category: "Headphones",
    brand: "Sony",
    price: 349,
    oldPrice: 399,
    rating: 4.8,
    reviewCount: 567,
    image: "/images/wh1000xm5.jpg",
    images: ["/images/wh1000xm5.jpg", "/images/wh1000xm5-2.jpg", "/images/wh1000xm5-3.jpg"],
    shortDescription: "Industry-leading noise cancellation with 30-hour battery.",
    fullDescription:
      "WH-1000XM5 sets the standard for noise-cancelling headphones, with two processors controlling eight microphones for exceptional cancellation and crystal-clear calls.",
    stock: 42,
    featured: true,
    trending: true,
    specifications: {
      Brand: "Sony",
      Model: "WH-1000XM5",
      "Driver Size": "30mm",
      "Battery Life": "30 hrs",
      Connectivity: "Bluetooth 5.2",
      "Noise Cancellation": "Adaptive ANC",
      Warranty: "1 Year",
    },
    colors: ["Black", "Silver"],
    warranty: "1 Year",
  },
  {
    id: 10,
    name: "Bose QuietComfort Ultra",
    slug: "bose-quietcomfort-ultra",
    category: "Headphones",
    brand: "Bose",
    price: 379,
    rating: 4.7,
    reviewCount: 312,
    image: "/images/qcultra.jpg",
    images: ["/images/qcultra.jpg", "/images/qcultra-2.jpg", "/images/qcultra-3.jpg"],
    shortDescription: "Immersive audio with world-class noise cancellation.",
    fullDescription:
      "QuietComfort Ultra delivers Bose's best-ever noise cancellation alongside Immersive Audio, wrapping you in rich, spatial sound wherever you go.",
    stock: 33,
    featured: false,
    trending: false,
    specifications: {
      Brand: "Bose",
      Model: "QuietComfort Ultra",
      "Driver Size": "35mm",
      "Battery Life": "24 hrs",
      Connectivity: "Bluetooth 5.3",
      "Noise Cancellation": "CustomTune ANC",
      Warranty: "1 Year",
    },
    warranty: "1 Year",
  },
  {
    id: 11,
    name: "Apple AirPods Pro 2",
    slug: "airpods-pro-2",
    category: "Headphones",
    brand: "Apple",
    price: 249,
    rating: 4.6,
    reviewCount: 892,
    image: "/images/airpodspro2.jpg",
    images: ["/images/airpodspro2.jpg", "/images/airpodspro2-2.jpg", "/images/airpodspro2-3.jpg"],
    shortDescription: "Adaptive Audio with industry-leading noise cancellation.",
    fullDescription:
      "AirPods Pro 2 feature Adaptive Audio, Personalized Spatial Audio, and up to 2x more Active Noise Cancellation than the previous generation.",
    stock: 56,
    featured: true,
    trending: false,
    specifications: {
      Brand: "Apple",
      Model: "AirPods Pro 2",
      "Driver Size": "11mm",
      "Battery Life": "6 hrs (30 w/ case)",
      Connectivity: "Bluetooth 5.3",
      "Noise Cancellation": "Active ANC",
      Warranty: "1 Year",
    },
    warranty: "1 Year",
  },

  // ─── TABLETS ────────────────────────────────────────────────────
  {
    id: 12,
    name: 'iPad Pro 12.9" M4',
    slug: "ipad-pro-129",
    category: "Tablets",
    brand: "Apple",
    price: 1099,
    rating: 4.8,
    reviewCount: 234,
    image: "/images/ipadpro129.jpg",
    images: ["/images/ipadpro129.jpg", "/images/ipadpro129-2.jpg", "/images/ipadpro129-3.jpg"],
    shortDescription: "The ultimate iPad experience powered by the M4 chip.",
    fullDescription:
      "iPad Pro is thinner, lighter, and more powerful than ever, with the blazing-fast M4 chip and a stunning Ultra Retina XDR display that brings creative work to life.",
    stock: 19,
    featured: true,
    trending: false,
    specifications: {
      Brand: "Apple",
      Model: "iPad Pro 12.9",
      Storage: "256GB",
      RAM: "8GB",
      Display: '12.9" Liquid Retina XDR',
      Battery: "Up to 10 hrs",
      Connectivity: "5G, Wi-Fi 6E",
      Warranty: "1 Year",
    },
    colors: ["Space Black", "Silver"],
    warranty: "1 Year",
  },
  {
    id: 13,
    name: "Samsung Galaxy Tab S9",
    slug: "galaxy-tab-s9",
    category: "Tablets",
    brand: "Samsung",
    price: 799,
    oldPrice: 899,
    rating: 4.5,
    reviewCount: 145,
    image: "/images/tabs9.jpg",
    images: ["/images/tabs9.jpg", "/images/tabs9-2.jpg", "/images/tabs9-3.jpg"],
    shortDescription: "Sleek Android tablet with an included S Pen.",
    fullDescription:
      "Galaxy Tab S9 brings a vivid Dynamic AMOLED display, an included S Pen, and IP68 water resistance to a premium, do-anything Android tablet.",
    stock: 22,
    featured: false,
    trending: true,
    specifications: {
      Brand: "Samsung",
      Model: "Galaxy Tab S9",
      Storage: "128GB",
      RAM: "8GB",
      Display: '11" Dynamic AMOLED 2X',
      Battery: "8400 mAh",
      Connectivity: "Wi-Fi 6E",
      Warranty: "1 Year",
    },
    warranty: "1 Year",
  },

  // ─── SMARTWATCHES ────────────────────────────────────────────────
  {
    id: 14,
    name: "Apple Watch Ultra 2",
    slug: "apple-watch-ultra-2",
    category: "Smartwatches",
    brand: "Apple",
    price: 799,
    rating: 4.7,
    reviewCount: 198,
    image: "/images/watchultra2.jpg",
    images: ["/images/watchultra2.jpg", "/images/watchultra2-2.jpg", "/images/watchultra2-3.jpg"],
    shortDescription: "The most rugged and capable Apple Watch ever.",
    fullDescription:
      "Apple Watch Ultra 2 is built for adventure, with a brighter display, longer battery life, and precision dual-frequency GPS for the most demanding environments.",
    stock: 16,
    featured: true,
    trending: false,
    specifications: {
      Brand: "Apple",
      Model: "Watch Ultra 2",
      Display: "49mm LTPO OLED",
      "Battery Life": "36 hrs",
      Connectivity: "GPS + Cellular",
      "Water Resistance": "100m",
      Warranty: "1 Year",
    },
    warranty: "1 Year",
  },
  {
    id: 15,
    name: "Samsung Galaxy Watch 6",
    slug: "galaxy-watch-6",
    category: "Smartwatches",
    brand: "Samsung",
    price: 349,
    rating: 4.4,
    reviewCount: 87,
    image: "/images/watch6.jpg",
    images: ["/images/watch6.jpg", "/images/watch6-2.jpg", "/images/watch6-3.jpg"],
    shortDescription: "Advanced health tracking in a sleek design.",
    fullDescription:
      "Galaxy Watch 6 delivers advanced sleep coaching, body composition analysis, and a vivid always-on display, all wrapped in a slim, comfortable case.",
    stock: 0,
    featured: false,
    trending: false,
    specifications: {
      Brand: "Samsung",
      Model: "Galaxy Watch 6",
      Display: "44mm AMOLED",
      "Battery Life": "40 hrs",
      Connectivity: "Bluetooth, Wi-Fi",
      "Water Resistance": "5ATM",
      Warranty: "1 Year",
    },
    warranty: "1 Year",
  },

  // ─── CAMERAS ─────────────────────────────────────────────────────
  {
    id: 16,
    name: "Canon EOS R6 Mark II",
    slug: "canon-eos-r6-ii",
    category: "Cameras",
    brand: "Canon",
    price: 2499,
    rating: 4.8,
    reviewCount: 76,
    image: "/images/eosr6ii.jpg",
    images: ["/images/eosr6ii.jpg", "/images/eosr6ii-2.jpg", "/images/eosr6ii-3.jpg"],
    shortDescription: "Full-frame mirrorless camera for hybrid shooters.",
    fullDescription:
      "EOS R6 Mark II is a versatile full-frame mirrorless camera offering blazing-fast autofocus, in-body stabilization, and stunning stills and video in one hybrid body.",
    stock: 9,
    featured: true,
    trending: false,
    specifications: {
      Brand: "Canon",
      Model: "EOS R6 Mark II",
      Sensor: "24.2MP Full-Frame CMOS",
      "ISO Range": "100–102400",
      Video: "4K 60p",
      "Continuous Shooting": "40 fps",
      Warranty: "2 Year",
    },
    warranty: "2 Year",
  },
  {
    id: 17,
    name: "Sony Alpha A7 IV",
    slug: "sony-alpha-a7iv",
    category: "Cameras",
    brand: "Sony",
    price: 2299,
    oldPrice: 2499,
    rating: 4.7,
    reviewCount: 64,
    image: "/images/a7iv.jpg",
    images: ["/images/a7iv.jpg", "/images/a7iv-2.jpg", "/images/a7iv-3.jpg"],
    shortDescription: "Versatile full-frame hybrid camera for photo and video.",
    fullDescription:
      "Alpha A7 IV is a true hybrid camera, balancing high resolution stills with pro-grade 10-bit 4K video, real-time tracking autofocus, and rugged build quality.",
    stock: 6,
    featured: false,
    trending: true,
    specifications: {
      Brand: "Sony",
      Model: "Alpha A7 IV",
      Sensor: "33MP Full-Frame CMOS",
      "ISO Range": "100–51200",
      Video: "4K 60p 10-bit",
      "Continuous Shooting": "10 fps",
      Warranty: "2 Year",
    },
    warranty: "2 Year",
  },

  // ─── SPEAKERS ────────────────────────────────────────────────────
  {
    id: 18,
    name: "JBL Charge 5",
    slug: "jbl-charge-5",
    category: "Speakers",
    brand: "JBL",
    price: 179,
    rating: 4.5,
    reviewCount: 432,
    image: "/images/charge5.jpg",
    images: ["/images/charge5.jpg", "/images/charge5-2.jpg", "/images/charge5-3.jpg"],
    shortDescription: "Portable Bluetooth speaker with powerful bass and powerbank.",
    fullDescription:
      "JBL Charge 5 delivers bold JBL Pro Sound with a built-in powerbank to charge your devices on the go, all in a tough, waterproof shell ready for any adventure.",
    stock: 48,
    featured: true,
    trending: false,
    specifications: {
      Brand: "JBL",
      Model: "Charge 5",
      "Output Power": "40W",
      "Battery Life": "20 hrs",
      Connectivity: "Bluetooth 5.1",
      "Water Resistance": "IP67",
      Warranty: "1 Year",
    },
    warranty: "1 Year",
  },
  {
    id: 19,
    name: "Sonos Era 100",
    slug: "sonos-era-100",
    category: "Speakers",
    brand: "Sonos",
    price: 249,
    rating: 4.6,
    reviewCount: 178,
    image: "/images/era100.jpg",
    images: ["/images/era100.jpg", "/images/era100-2.jpg", "/images/era100-3.jpg"],
    shortDescription: "Compact smart speaker with rich, room-filling sound.",
    fullDescription:
      "Era 100 packs two custom-designed drivers into a compact frame, delivering deep bass and crisp detail, with easy setup via Wi-Fi and Bluetooth.",
    stock: 29,
    featured: false,
    trending: false,
    specifications: {
      Brand: "Sonos",
      Model: "Era 100",
      "Output Power": "2x custom drivers",
      Connectivity: "Wi-Fi, Bluetooth 5.0",
      "Voice Control": "Built-in mic",
      Warranty: "1 Year",
    },
    warranty: "1 Year",
  },

  // ─── GAMING ACCESSORIES ──────────────────────────────────────────
  {
    id: 20,
    name: "Logitech G Pro X Superlight",
    slug: "logitech-g-pro-x-superlight",
    category: "Gaming Accessories",
    brand: "Logitech",
    price: 149,
    rating: 4.8,
    reviewCount: 521,
    image: "/images/gprox.jpg",
    images: ["/images/gprox.jpg", "/images/gprox-2.jpg", "/images/gprox-3.jpg"],
    shortDescription: "Ultra-lightweight wireless gaming mouse used by esports pros.",
    fullDescription:
      "G Pro X Superlight is built for competitive gaming, shedding every unnecessary gram for a featherweight, wireless mouse trusted by the world's top esports pros.",
    stock: 37,
    featured: false,
    trending: true,
    specifications: {
      Brand: "Logitech",
      Model: "G Pro X Superlight",
      Sensor: "HERO 25K",
      DPI: "25,600",
      "Battery Life": "95 hrs",
      Connectivity: "LIGHTSPEED Wireless",
      Warranty: "2 Year",
    },
    warranty: "2 Year",
  },

  // ─── MONITORS ────────────────────────────────────────────────────
  {
    id: 21,
    name: 'ASUS ROG Strix 27" Monitor',
    slug: "asus-rog-strix-27-monitor",
    category: "Monitors",
    brand: "Asus",
    price: 449,
    oldPrice: 499,
    rating: 4.6,
    reviewCount: 156,
    image: "/images/rogstrix27.jpg",
    images: ["/images/rogstrix27.jpg", "/images/rogstrix27-2.jpg", "/images/rogstrix27-3.jpg"],
    shortDescription: "High-refresh gaming monitor with stunning visuals.",
    fullDescription:
      "ROG Strix 27\" delivers buttery-smooth, tear-free gaming with a fast IPS panel, vivid color accuracy, and a sleek design built for serious setups.",
    stock: 13,
    featured: true,
    trending: false,
    specifications: {
      Brand: "Asus",
      Model: "ROG Strix 27",
      "Display Size": '27"',
      Resolution: "2560x1440",
      "Refresh Rate": "165Hz",
      "Panel Type": "IPS",
      Warranty: "3 Year",
    },
    warranty: "3 Year",
  },
];